### PR TITLE
Replace docker container with dependency setup script

### PR DESCRIPTION
**Pull request by jbagnara**
The intent for this pull request is to replace the docker files in our repo with a bash install script. We've discovered that docker will not be suitable for the different modules of our project and that we would be better off without containerization. setup.sh is a one click script that should allow the project to be run on a jetson nano without any further setup.

torchvision does not (and to my knowledge cannot) include a version in jetson-requirements.txt. I assume this is just a connector or something because torchvision v0.7.0 is installed to the system.

### CODE REVIEW

**Comment by jbagnara** [comment]
> Looks good just a few things.
> 
>     1. How does this affect our dev environments? as we continue to test, tweak and deploy we need to be able to reproduce bugs when they occur. can you provide documentation on how everyone should modify their environments.
> 
>     2. Can you update the travis script. obviously now travis using conda is outdated so this needs to be fixed to ensure future builds aren't introducing breaking changes.

These changes only affect the environment on the jetson-nano. This will not affect any other members because everyone else is running on x86 machines, which will still be using conda. Likewise, travis is unaffected and this pr has passed the travis script.

**Comment by stephend017** [comment]
> These changes only affect the environment on the jetson-nano. 

this is only partly true. Yes this change only directly affects the jetson-nano. My main concern was being able to reproduce bugs. I know that only limited tests have been conducted with the jetson if any. If and when a bug occurs on the jetson I want to ensure that we wont need a jetson to debug the issue and provide a fix. 

The reason I brought this up was because we need this script because docker worked on dev environments, but not jetson or prod environments. Hence this problem could've been avoided altogether had we done more research. 

I'm gonna trust you here that no changes need to be made but I want this thread documented that we as a team are aware these environments are different and that this project has the potential to pass all tests on our dev machines and travis, but fail on jetson.

**Comment by jbagnara** [comment]
> docker worked on dev environments, but not jetson or prod environments.

The docker container was only ever intended for the prod environment on the jetson. It was impossible for us to share a docker container between both environments because the jetson uses a different cpu architecture than our dev environments and we don't have any kind of vm set up. That said, the docker container never really worked suitably on any environment.

> this project has the potential to pass all tests on our dev machines and travis, but fail on jetson.

This has always been the case. I don't know how to fix this. Maybe we could set up a vm for Travis? I will try and work with a team member more knowledgeable with our testing suite to try and fix this.

**Comment by stephend017** [comment]
> This has always been the case. I don't know how to fix this. Maybe we could set up a vm for Travis? I will try and work with a team member more knowledgeable with our testing suite to try and fix this.

So this exact problem is why docker was created. I think a long term solution would be to setup a dedicated jetson that we can have travis dynamically load a build onto and then execute the test suite on the jetson and return the results to travis. *However* I recognize that this is a difficult and time consuming process and might not get completed before this is deployed.

**Comment by jbagnara** [comment]
>  I think a long term solution would be to setup a dedicated jetson that we can have travis dynamically load a build onto and then execute the test suite on the jetson and return the results to travis. However I recognize that this is a difficult and time consuming process and might not get completed before this is deployed.

I have added a trello card for this. It may be something to consider for the fall semester.

**Comment by stephend017** [comment]
Thats good. especially since I think Dr. Lu wants this team to streamline development and make deployment much easier and faster specifically in the cases of masks.

**Pull request merged**
